sudo: false

language: node_js

node_js:
  - "iojs"
  - "0.12"
  - "0.10"
  - "4"
  - stable

script: grunt test -v --stack -d

before_install:
  - export CHROME_BIN=chromium-browser
  - npm install -g grunt-cli bower karma-cli
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - npm install

matrix:
  fast_finish: true

# Gitter notifications
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e0a2c5381a9eb60c459d
    on_success: change
    on_failure: always
    on_start: false
