language: node_js

sudo: required

dist: trusty

node_js:
  - "5.0.0"
  - "6.0.0"
  - stable

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install -g grunt-cli web-component-tester bower polylint
  - bower i

before_script:
  - polylint

script:
  - grunt test -v --stack -d

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules
    - bower_components

# Gitter notifications
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e0a2c5381a9eb60c459d
    on_success: change
    on_failure: always
    on_start: false
