sudo: false
cache: bundler

language: node_js

node_js:
  - 'iojs'
  - "0.12"
  - "0.10"

script: grunt test -v --stack -d

before_install:
  - export CHROME_BIN=chromium-browser
  - npm install -g grunt-cli bower karma
  - gem install bundler
  - bundle install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install
  - bower install

# Gitter notifications
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0c84c04a34c898b48276
    on_success: change
    on_failure: always
    on_start: false
